runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "mssappbucket"

handlers:
- url: /
  static_files: dist/mssApp/index.html
  upload: dist/mssApp/index.html

- url: /
  static_dir: dist/mssApp